[package]
name = "utmp"
version = "0.0.1"
authors = ["Jihyeok Seo <me@limeburst.net>"]
description = "utmp(x) file parser."
homepage = "https://github.com/limeburst/utmp-rust"
repository = "https://github.com/limeburst/utmp-rust"
readme = "README.md"
license = "MIT"

[dependencies]
time = "*"
